//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR16
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commands
    {
        public int Id { get; set; }
        public string Command_Name { get; set; }
        public int City_ID { get; set; }
        public Nullable<int> Match_ID { get; set; }
        public Nullable<int> Varehouse_ID { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Matches Matches { get; set; }
        public virtual Varehouses Varehouses { get; set; }
    }
}
